{
  pkgs,
  pkgsUnstable,
  ...
}: {
  home.packages = with pkgs;
    [
      alejandra
      android-tools
      alsa-utils
      ani-cli
      btop
      calibre
      docker-compose
      direnv
      discord
      dbeaver-bin
      mate.eom
      fastfetch
      fortune
      flameshot
      fatsort
      ffmpeg
      heroic
      hugo
      just
      krabby
      mangohud
      micro
      nodejs_24
      protonup-ng
      simplescreenrecorder
      yt-dlp
      blanket
      libreoffice
      kdePackages.kdenlive
      nicotine-plus
      skyscraper
      sqlite
      temurin-bin
      eclipses.eclipse-jee
      dmenu
      i3status
      vlc
      lxappearance
      kanagawa-gtk-theme
      kanagawa-icon-theme
      psmisc
      source-code-pro
    ]
    ++ [
      pkgsUnstable.vscode-fhs
    ];
}
